version: 1.2
workflows:
  - name: intro-short
    subclass: GXFORMAT2
    primaryDescriptorPath: topics/introduction/tutorials/galaxy-intro-short/workflows/Galaxy-Workflow-galaxy-intro-short.ga
    testParameterFiles:
  - name: intro-everyone
    subclass: GXFORMAT2
    primaryDescriptorPath: topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow.ga
    testParameterFiles:
